export const REQUEST_DATA = 'REQUEST_DATA';
export const REQUEST_DATA_FAILED = 'REQUEST_DATA_FAILED';
export const FETCH_DATA = 'FETCH_DATA';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
